---
title: "README"
format: html
editor: visual
---

## Explore languages spoken in the United States

You want to explore, visualize, and render a report using the [tidyverse](https://www.tidyverse.org/) and [Quarto](https://quarto.org/). This template creates a report that explores data on languages spoken at home in the United States.

To interact with this template, you can:

-   **Run the code chunks in `languages.qmd`**, a Quarto document that imports, explores, and visualizes the language data. To run a code chunk, press the green "play" button in the upper-right corner of the chunk.

-   **Edit any code chunk in `languages.qmd`**, then run that chunk again to see the results of your changes.

-   **Render `languages.qmd`** to create an HTML report. You can render Quarto documents by pressing the *Render* button at the top of the editor.

### Data

This template uses data on languages other than English spoken at home in the United States. The data comes from the 2018 5-year [American Community Survey](https://www.census.gov/programs-surveys/acs).

### Files

There are multiple files you can explore and interact with:

-   `languages.qmd`: A [Quarto](https://quarto.org/) document that imports, explores, and visualizes the language data. If you'd like to explore the data yourself, start here!

-   `data/languages.csv`: The cleaned data file, which is ready for analysis.

-   `data/languages_raw.csv`: The raw data file.

-   `data/languages.R`: A script that turns the raw data into the cleaned data.

### Packages

This template includes the following packages, among others:

-   tidyverse (meta-package)
-   ggplot2
-   dplyr
-   tidyr
-   readr
-   purrr
-   tibble
-   stringr
-   forcats
-   tidyr
